apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-iany
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-iany
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-iany
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-iany
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-iany
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zaec-tenant/rhtap-demo-app/hacbs-test-project-iany@sha256:5d1b6dc7353932765149ea4c1ac8eae27afbe9602ba51024b46c261b5eb4a2a5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
