apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iany
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zaec-tenant/rhtap-demo-app/hacbs-test-project-iany@sha256:5d1b6dc7353932765149ea4c1ac8eae27afbe9602ba51024b46c261b5eb4a2a5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
